### ISSUE TITLE
Whitelist issue in ClusterV2 related contracts

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-contract#29]
Previously, when testing PR #20, the latest update made to the contracts was the addition of ClusterV1 to the code hash whitelist. This fix addressed the issue where SporeV2 and ClusterProxy were unable to reference ClusterV1.

However, this fix also introduced a new issue. Here's the situation:

- ClusterV2 cannot be referenced by SporeV2 or ClusterProxy, resulting in a 5 (ClusterCellNotInDep) error.
- ClusterV1 can be referenced by SporeV2 or ClusterProxy, and the generated cells can be transferred/melted as expected.

**Comment by ashuralyk** [comment]
@ShookLyngs is issue be fixed ?

**Comment by ShookLyngs** [comment]
This issue has been fixed in #27, marking the issue as completed.
