### ISSUE TITLE
 contract size increased ~ 40KB after PR #28

### ISSUE THREAD

**Issue by Flouse** [sporeprotocol/spore-contract#34]
## Description
After PR #28, the contract size has increased by ~40K.

```js
ls build/release/ -lh

total 644K
-rwxr-xr-x 1 ubuntu docker  70K Jan  8 08:07 cluster
-rwxr-xr-x 1 ubuntu docker  82K Jan  8 08:08 cluster_agent
-rwxr-xr-x 1 ubuntu docker  68K Jan  8 08:07 cluster_proxy
-rw-r--r-- 1 ubuntu docker 262K Jan  8 08:07 libckblua.so
-rwxr-xr-x 1 ubuntu docker 110K Jan  8 08:08 spore
-rwxr-xr-x 1 ubuntu docker  41K Jan  8 08:07 spore_extension_lua

```

This might be a **Low-Priority** issue.

It may impact the Stage 1 deployment plan listed in https://dao.ckb.community/thread/vot-spore-protocol-mainnet-launch-sponsorship-proposal-48305
```
Stage 1:

Spore   (73,342 CKBytes)
Cluster (37,150 CKBytes)
```

**Comment by ashuralyk** [comment]
good point, I guess co-build crate can introduce minimal features to meet the minimal demand from contract

**Comment by ashuralyk** [comment]
@quake please mark this issue for our further optimization on `co-build-transaction` crate

**Comment by quake** [comment]
please change lto from false to true and see if we can get a smaller binary or not.
```diff
- lto = false
+ lto = true
```

**Comment by ashuralyk** [comment]
> please change lto from false to true and see if we can get a smaller binary or not.
> 
> ```diff
> - lto = false
> + lto = true
> ```

result is cool @Flouse 

<img width="635" alt="image" src="https://github.com/sporeprotocol/spore-contract/assets/3871265/650ea3e1-41e0-43fc-b8c8-15eb88bd8de8">
