### ISSUE TITLE
Potential silent runtime errors caused by unchecked length

### ISSUE THREAD

**Issue by yangby-cryptape** [sporeprotocol/spore-contract#40]
### Description

Without counting, just following your intuition, can you answer the following questions?

- The length of the following string.

  https://github.com/sporeprotocol/spore-contract/blob/65a9d41d1ee6cfa49f91d6b62c20585677d062c7/deployment/frozen/testnet.toml#L4

- Is the above string as the same as the following string?

  ```
  598d793defef36e2eeba54a9b45130e4ca92822e1d12193671f490950c3b856080
  ```
I guess you are not able for above questions.

---

The following function doesn't check the length:

https://github.com/sporeprotocol/spore-contract/blob/65a9d41d1ee6cfa49f91d6b62c20585677d062c7/lib/build/src/lib.rs#L19-L23

And I checked its callers, they doesn't, too.

So, even the string in the configuration files are incorrect, for example, 2 more characters added by typo, **the error won't be raised**.

---

You should change the following field:

https://github.com/sporeprotocol/spore-contract/blob/65a9d41d1ee6cfa49f91d6b62c20585677d062c7/lib/build/src/lib.rs#L7

to:

```rust
    code_hash_list: Vec<[u8; 32]>,
```

and implement deserialization for it.

**Comment by ashuralyk** [comment]
good reminder, thx
