### ISSUE TITLE
CI: the push event of `devnet` workflow is always using master branch

### ISSUE THREAD

**Issue by Flouse** [sporeprotocol/spore-contract#45]
The push event of `devnet` workflow is always using master branch, which is unexpected.

See https://github.com/sporeprotocol/spore-contract/actions/runs/7490246526/job/20388642780#step:8:12

## Related discussion
- https://github.com/sporeprotocol/spore-contract/pull/32#discussion_r1448254333

## Problem
- [ ] The shell script [prepare.sh](https://github.com/sporeprotocol/spore-devenv/blob/9db6fe2bbffa1154c5b16ead319aa98df5494002/prepare.sh) from the spore-devenv repository does NOT support `GITHUB_REF` as an argument.

**Comment by ashuralyk** [comment]
https://github.com/sporeprotocol/spore-contract/actions/runs/7475754263/job/20344857143

this PR we used as an experiment to check how the $GITHUB_HEAD_REF works, and this action result shows it meets our expectation

**Comment by ashuralyk** [comment]
please see this: https://github.com/sporeprotocol/spore-contract/actions/runs/7499267970/job/20415733888?pr=28

our fresh PR failed on `Devnet` CI shows this command works fine

**Comment by Flouse** [comment]
https://github.com/sporeprotocol/spore-contract/blob/f0a0ef3cb07e9d768e5674d7d2357c732808c0b2/.github/workflows/devnet.yaml#L6-L9

I see.
`push event` is only applied on master branch now.
