### ISSUE TITLE
-1 When attempting to create Spore with Cluster V1

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-contract#47]
Currently, when attempting to create a Spore V2 with a Cluster V1, the Spore type throws a -1 error.

This issue was not encountered during devnet testing as v1 tests are currently only available on testnet. I discussed this with @Dawn-github, and we believe that adding v1 contracts to the spore-devenv should resolve this testing problem.

**Comment by ashuralyk** [comment]
> we believe that adding v1 contracts to the spore-devenv should resolve this testing problem

can you describe further more about this?

**Comment by ShookLyngs** [comment]
> can you describe further more about this?

This error was not found in the devnet testing, because in devnet mode, v1 tests are skipped.
If we can add v1 version of the contracts to the spore-devenv, we can also test v1 compatibility in devnet mode.

**Comment by Dawn-githup** [comment]
> > can you describe further more about this?
> 
> This error was not found in the devnet testing, because in devnet mode, v1 tests are skipped. If we can add v1 version of the contracts to the spore-devenv, we can also test v1 compatibility in devnet mode.

- The devenv project adds the ability to deploy spore_v1

https://github.com/sporeprotocol/spore-devenv/pull/4
