### ISSUE TITLE
Different machine compiled different contract binary

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-contract#53]
# Description
different contract binary means different `code_hash` value, which we referred to define our version of contracts

**Comment by Flouse** [comment]
- https://github.com/sporeprotocol/spore-contract/pull/52#issuecomment-1909215320

**Comment by ashuralyk** [comment]
now we can make reproduction process fixed on CI workflow to prevent this happening after then, see https://github.com/sporeprotocol/spore-contract/pull/54
